#!/bin/bash

set -ex

STABILITY[2]='stable'
STABILITY[3]='stable'
STABILITY[4]='RC'

CONSTRAIN[2]='symfony/console:^2.8'
CONSTRAIN[3]='symfony/console:^3'
CONSTRAIN[4]='symfony/console:^4'

for SYMFONY in 2 3 4 ; do

  dir=tests/symfony${SYMFONY}

  echo "### Create $dir/composer.json to test Symfony ${SYMFONY}"
  mkdir -p $dir
  cp composer.json $dir

  # If our composer.json has set a platform php version, unset it.
  composer -n --working-dir=$dir config --unset platform.php

  # Temporarily set our vendor directory to 'vendor'
  composer -n --working-dir=$dir config vendor-dir vendor

  # Set an appropriate minimum stability for this version of Symfony
  composer -n --working-dir=$dir config minimum-stability "${STABILITY[$SYMFONY]}"

  # Add a constraint to limit the Symfony version
  composer -n --working-dir=$dir require --dev --no-update "${CONSTRAIN[$SYMFONY]}"

  # Create the composer.lock file. Ignore the vendor directory created.
  composer -n --working-dir=$dir update --no-scripts

  # Set the vendor directory to its final desired location.
  composer -n --working-dir=$dir config vendor-dir '../../vendor'

done
