#!/bin/bash

SYMFONY=${1-4}

dir=tests/symfony${SYMFONY}
if [ ! -d "$dir" ] ; then
  echo "Specified Symfony verison '${SYMFONY}' not supported."
  exit 1
fi

echo "Switch to Symfony ${SYMFONY}"
composer -n --working-dir=$dir install
composer -n --working-dir=$dir licenses
